name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    # 新增 pnpm 专用安装步骤
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      run: pnpm i

    - name: Build project
      run: pnpm run build:web

    - name: Create data directory
      run: |
        mkdir -p build/data

    - name: Archive build folder
      run: zip -r build.zip build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-package
        path: build.zip
