name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y curl git bash node zip gcc gmake python3
          npm intsall -g pnpm@9.15.5   
        run: |
          #get sourcecode
          echo "=====================Pull Packages====================="
          git clone https://github.com/SkySight-666/any-listen-freeBSD.git
          cd any-listen-freeBSD
          #install modules
          echo "=====================Install Modules====================="
          pnpm i
          #builid website
          echo "=====================Build Website====================="
          pnpm run build:web
          cd build
          mkdir data
          cd ..
          #package output
          echo "=====================Package Output====================="
          zip -r Output.zip build
          mkdir ../output
          mv Output.zip ../output
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Any_Listen_FreeBSD
        path: |
          output/*
    

          



