jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start FreeBSD VM
        uses: vmactions/freebsd-vm@v1.0.0
        with:
          iso: https://download.freebsd.org/ftp/releases/VM-IMAGES/13.2-RELEASE/amd64/Latest/FreeBSD-13.2-RELEASE-amd64.qcow2.xz
          memory: 4096
          ssh: true  # 关键！启用 SSH 服务
          ssh-user: root  # 默认用户
          ssh-password: freebsd  # 默认密码

      - name: Install SSH Tools in VM
        shell: bash  # 使用宿主机的 shell
        run: |
          # 通过 QEMU Guest Agent 执行虚拟机内命令
          echo "Installing OpenSSH..."
          qemu-ga -c 'sudo pkg install -y openssh rsync'

          # 启动 SSH 服务
          qemu-ga -c 'sudo service sshd start'

      - name: Prepare VM Environment
        shell: ssh  # 使用原生 SSH 连接
        env:
          SSH_PORT: 2222  # 默认转发端口
        run: |
          sudo pkg update -f
          sudo pkg install -y node18 npm-node18 git-lite
          sudo npm install -g pnpm
          rsync -avz -e "ssh -p $SSH_PORT" /github/workspace/ root@localhost:/build

      - name: Build Project
        shell: ssh
        run: |
          cd /build
          pnpm install
          pnpm run build:web
          tar -czvf freebsd-build.tar.gz build/
