name: FreeBSD Build and Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Package on FreeBSD
    env:
      NODE_ENV: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build in FreeBSD VM
      uses: vmactions/freebsd-vm@v1.1.9
      with:
        usesh: true
        prepare: |
          pkg install -y node npm pnpm
        run: |
          # 安装依赖并构建
          pnpm install
          pnpm run build:web
          
          # 创建目录结构
          cd build
          mkdir -p data
          echo "module.exports = {}" > config.cjs
          cd ..
          
          # 打包构建产物
          tar -czvf build-artifact.tar.gz build/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-package
        path: build-artifact.tar.gz
