name: FreeBSD Native Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start FreeBSD VM
        uses: vmactions/freebsd-vm@v0
        with:
          iso: https://download.freebsd.org/releases/amd64/13.2-RELEASE/FreeBSD-13.2-RELEASE-amd64.qcow2.xz
          memory: 4096
          cpu: 4

      - name: Prepare VM Environment
        shell: vmssh
        run: |
          # 安装基础工具
          sudo pkg update -y
          sudo pkg install -y node npm git

          # 安装 pnpm
          sudo npm install -g pnpm

          # 同步宿主机代码到虚拟机
          rsync -avz /host/ ${{ github.workspace }}/

      - name: Build Project
        shell: vmssh
        run: |
          cd ${{ github.workspace }}
          pnpm install
          pnpm run build:web

          # 创建打包目录
          mkdir -p dist
          cd build
          tar -czvf ../dist/freebsd-build.tar.gz .

      - name: Export Artifacts
        shell: vmssh
        run: |
          # 将产物复制到共享目录
          cp ${{ github.workspace }}/dist/freebsd-build.tar.gz /host/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: freebsd-build
          path: freebsd-build.tar.gz
